#language:
 # python
#after_success:
  #- bash <(curl -s https://codecov.io/bash)


language: python
# cache: pip
notifications:
  email: false
dist: xenial
sudo: false
python:
  - 2.7
  - pypy
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - pypy3
matrix:
  include:
    - python: 2.7
      dist: trusty
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-requests
            - python-coverage
            - python-mock
    - python: 3.8
      dist: xenial
      script: make format

install:
  - pip install -r requirements.txt
script:
  - make reinstall
  - make test
  # - pytest tests/test.py --cov=codecov
after_success:
  - codecov
